# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e407ec080f807963005657917aa3fbe5db4f2bdaeac5a8a9fee271db466d462e6df41caf764b132362659776c391f7cc23e668e3add5acf2eb859937922f09f9

test:
  secret_key_base: 64393022bcfb7562cd71316414146bd6ad773832b4a34d5e1ae02575452ac715e7e68f87e0a20dcd368f68ecbb8c3a1677ee414c26015ec1af6be28513a521e4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
